ARG SR_LINUX_RELEASE
FROM registry.srlinux.dev/pub/srlinux:$SR_LINUX_RELEASE

# Install gnmic like this
RUN sudo curl -sL https://github.com/karimra/gnmic/releases/download/v0.14.1/gnmic_0.14.1_Linux_x86_64.rpm -o /tmp/gnmic.rpm && sudo yum localinstall -y /tmp/gnmic.rpm

# Add a binary from another image
# COPY --from=paris-traceroute /usr/local/bin/paris-* /usr/local/bin/

COPY 42_sr_copy_custom_appmgr.sh /opt/srlinux/bin/bootscript/

# COPY ./appmgr/ /etc/opt/srlinux/appmgr/ # doesn't work, using a script to copy at runtime
COPY ./appmgr/ /home/appmgr
